language: erlang

os:
  - linux

otp_release:
   - 22.3
   - 23.1

notifications:
  email: rtb-team+travis@adroll.com

script:
  - rebar3 local upgrade
  - export PATH=/home/travis/.cache/rebar3/bin:$PATH
  - rebar3 --version
  - erl -version
  - rebar3 format --verify
  - DEBUG=1 rebar3 test
